- type: job
  id: GuardianNt
  name: страж клинка
  description: Встань на защиту командования станции со своим крутым мечом и способностями!
  playTimeTracker: JobGuardianNt
  requirements:
    - !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 36000 # 10 hours
    - !type:RoleTimeRequirement
      role: JobCaptain
      time: 36000 # 10 hours
    - !type:RoleTimeRequirement
      role: JobIAA
      time: 36000 # 10 hours # ! Почему так чертовски много?
    - !type:RoleTimeRequirement
      role: JobDetective
      time: 18000 # 5 hours
  startingGear: GuardianNtGear
  icon: "JobIconGuardianNt"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: Force
    - type: ForceUser
      preset: Guardian

- type: startingGear
  id: GuardianNtGear
  equipment:
    id: GuardianNtPDA
    ears: ClothingHeadsetGuardianNtAlt
    gloves: ClothingHandsGlovesCombat
    eyes: ClothingEyesGlassesSecurity
