# ATLAS CONFIG

# [config]
# presets = "Stories/atlas"

[adminlogs]
server_name = "Space Stories - Atlas ğŸ—ºï¸"

[game]
hostname         = "ğŸ“š Space Stories - Atlas ğŸ—ºï¸ [TTS]"
soft_max_players = 100

[hub]
tags = "lang:ru,rp:med,region:eu_e"
