# DEVELOP CONFIG

# [config]
# presets = "Stories/develop"

[whitelist]
enabled = true
reason = "ะขัะตะฑัะตััั ัะฐะทัะตัะตะฝะธะต ะฝะฐ ะฟะพะดะบะปััะตะฝะธะต ะบ ััะพะผั ัะตัะฒะตัั."

[adminlogs]
enabled = false

[game]
hostname = "๐ Space Stories - Develop โ"
role_timers = false
desc = "โ๏ธ ะญัะพ ัะตัะฒะตั ๐ฆ๐ฝ๐ฎ๐ฐ๐ฒ ๐ฆ๐๐ผ๐ฟ๐ถ๐ฒ๐ ะดะปั ัะฐะทัะฐะฑะพััะธะบะพะฒ."

[rules]
time = 0.0
