# MAPPERS CONFIG

# [config]
# presets = "Stories/mappers"

[whitelist]
enabled = true

[adminlogs]
enabled = false

[game]
hostname = "ğŸ“š Space Stories - Mappers ğŸ—º"
role_timers = false
desc = "âš™ï¸ Ğ­Ñ‚Ğ¾ ÑĞµÑ€Ğ²ĞµÑ€ ğ—¦ğ—½ğ—®ğ—°ğ—² ğ—¦ğ˜ğ—¼ğ—¿ğ—¶ğ—²ğ˜€ Ğ´Ğ»Ñ Ğ¼Ğ°Ğ¿Ğ¿ĞµÑ€Ğ¾Ğ²."

[rules]
time = 0.0
