# ĞŸÑ€ĞµĞ´ÑƒÑÑ‚Ğ°Ğ½Ğ¾Ğ²ĞºĞ° ĞºĞ¾Ğ½Ñ„Ğ¸Ğ³ÑƒÑ€Ğ°Ñ†Ğ¸Ğ¸, Ğ¸ÑĞ¿Ğ¾Ğ»ÑŒĞ·ÑƒĞµĞ¼Ğ°Ñ Ğ½Ğ° ÑĞµÑ€Ğ²ĞµÑ€Ğµ Space Stories Stage.
# Ğ—Ğ°Ğ³Ñ€ÑƒĞ¶Ğ°ĞµÑ‚ÑÑ Ğ¿ĞµÑ€ĞµĞ´ Ğ½Ğ°ÑÑ‚Ñ€Ğ¾Ğ¹ĞºĞ°Ğ¼Ğ¸ ĞºĞ¾Ğ½Ñ„Ğ¸Ğ³ÑƒÑ€Ğ°Ñ†Ğ¸Ğ¸, ÑĞ¿ĞµÑ†Ğ¸Ñ„Ğ¸Ñ‡Ğ½Ñ‹Ğ¼Ğ¸ Ğ´Ğ»Ñ ÑĞµÑ€Ğ²ĞµÑ€Ğ°.

# [config]
# presets = "Stories/stage"

[admin]
admins_count_in_playercount = true
deadmin_on_join = false

[adminlogs]
enabled = false

[game]
hostname = "ğŸ“š Space Stories - Stage âš™"
desc = """
                  ğŸ“• ğ—¦ğ—½ğ—®ğ—°ğ—² ğ—¦ğ˜ğ—¼ğ—¿ğ—¶ğ—²ğ˜€ - Ğ¡ĞµÑ€Ğ²ĞµÑ€, ĞºĞ¾Ñ‚Ğ¾Ñ€Ñ‹Ğ¹ Ñ†ĞµĞ½Ğ¸Ñ‚ Role Play, ÑĞ¾Ğ·Ğ´Ğ°Ğ²Ğ°Ğ¹ ÑĞ²Ğ¾Ğ¸ Ğ¸ÑÑ‚Ğ¾Ñ€Ğ¸Ğ¸ Ñƒ Ğ½Ğ°Ñ! ğŸ“˜
â€¢â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ âœ§ â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â€¢
  ğŸ‘¥ â‹® Ğ¡ĞµÑ€Ğ²ĞµÑ€ Ğ´Ğ»Ñ Ğ¿ĞµÑ€ÑĞ¾Ğ½Ğ°Ğ»Ğ° Ğ¿Ñ€Ğ¾ĞµĞºÑ‚Ğ° Space Stories ğŸ“š
â€¢â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ âœ§ â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â€¢
                                            ğŸ“š ĞŸÑ€Ğ¸ÑĞ¾ĞµĞ´Ğ¸Ğ½ÑĞ¹Ñ‚ĞµÑÑŒ Ğº Ğ½Ğ°ÑˆĞµĞ¼Ñƒ Ğ´Ñ€ÑƒĞ¶Ğ½Ğ¾Ğ¼Ñƒ ÑĞ¾Ğ¾Ğ±Ñ‰ĞµÑÑ‚Ğ²Ñƒ ğŸ“š"""
maxplayers = 10
soft_max_players = 10
role_timers = false
role_whitelist = false

[whitelist]
enabled = true

[rules]
time = 0.0
