# BASE STORIES CONFIG

# [config]
# presets = "Stories/stories"

[game]
desc              = """
                  ğŸ“• ğ—¦ğ—½ğ—®ğ—°ğ—² ğ—¦ğ˜ğ—¼ğ—¿ğ—¶ğ—²ğ˜€ - Ğ¡ĞµÑ€Ğ²ĞµÑ€, ĞºĞ¾Ñ‚Ğ¾Ñ€Ñ‹Ğ¹ Ñ†ĞµĞ½Ğ¸Ñ‚ Role Play, ÑĞ¾Ğ·Ğ´Ğ°Ğ²Ğ°Ğ¹ ÑĞ²Ğ¾Ğ¸ Ğ¸ÑÑ‚Ğ¾Ñ€Ğ¸Ğ¸ Ñƒ Ğ½Ğ°Ñ! ğŸ“˜
â€¢â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ âœ§ â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â€¢
  ğŸŒ  â‹® Ğ¡ĞµÑ€Ğ²ĞµÑ€ ÑĞ¾ ÑÑ€ĞµĞ´Ğ½Ğ¸Ğ¼ ÑƒÑ€Ğ¾Ğ²Ğ½ĞµĞ¼ Ñ‚Ñ€ĞµĞ±Ğ¾Ğ²Ğ°Ğ½Ğ¸Ğ¹ Ğº Ñ€Ğ¾Ğ»ĞµĞ²Ğ¾Ğ¼Ñƒ Ğ¾Ñ‚Ñ‹Ğ³Ñ€Ñ‹ÑˆÑƒ.
  ğŸ©º â‹® Ğ¥Ğ¸Ñ€ÑƒÑ€Ğ³Ğ¸Ñ - ÑƒĞ½Ğ¸ĞºĞ°Ğ»ÑŒĞ½Ğ°Ñ Ğ¼ĞµÑ…Ğ°Ğ½Ğ¸ĞºĞ° Ğ¿Ğ¾Ğ²Ñ€ĞµĞ¶Ğ´ĞµĞ½Ğ¸Ğ¹ Ğ¾Ñ€Ğ³Ğ°Ğ½Ğ¾Ğ² Ğ¸ Ğ²Ğ¾Ğ·Ğ¼Ğ¾Ğ¶Ğ½Ğ¾ÑÑ‚ÑŒ Ğ¸Ñ… Ğ¿ĞµÑ€ĞµÑĞ°Ğ´ĞºĞ¸.
  ğŸ” â‹® ĞšĞ¾ÑĞ¼Ğ¸Ñ‡ĞµÑĞºĞ°Ñ Ñ‚ÑÑ€ÑŒĞ¼Ğ° - Ğ¾Ñ‚Ğ´Ğ°Ğ»ĞµĞ½Ğ½Ñ‹Ğ¹ Ğ¾Ğ±ÑŠĞµĞºÑ‚ Ğ² ĞºĞ¾ÑĞ¼Ğ¾ÑĞµ, ÑĞ¾Ğ´ĞµÑ€Ğ¶Ğ°Ñ‰Ğ¸Ğ¹ Ğ¾Ğ¿Ğ°ÑĞ½Ñ‹Ñ… Ğ¿Ñ€ĞµÑÑ‚ÑƒĞ¿Ğ½Ğ¸ĞºĞ¾Ğ².
  ğŸŒ‘ â‹® Ğ¢ĞµĞ½ĞµĞ¼Ğ¾Ñ€Ñ„ - Ğ¿Ğ¾Ğ»ÑƒĞ±Ğ¾Ğ³, Ğ±Ğ¾ÑÑ‰Ğ¸Ğ¹ÑÑ ÑĞ²ĞµÑ‚Ğ°, Ğ¿Ğ¾Ñ€Ğ°Ğ±Ğ¾Ñ‰Ğ°ÑÑ‰Ğ¸Ğ¹ ÑĞºĞ¸Ğ¿Ğ°Ğ¶ Ñ Ñ†ĞµĞ»ÑŒÑ Ğ·Ğ°Ñ…Ğ²Ğ°Ñ‚Ğ¸Ñ‚ÑŒ Ğ³Ğ°Ğ»Ğ°ĞºÑ‚Ğ¸ĞºÑƒ.
  âš”ï¸ â‹® Ğ¡Ñ‚Ñ€Ğ°Ğ¶ ĞšĞ»Ğ¸Ğ½ĞºĞ° - Ğ²Ğ¾Ğ¸Ğ½ ÑĞ²ĞµÑ‚Ğ°, Ğ·Ğ°Ñ‰Ğ¸Ñ‰Ğ°ÑÑ‰Ğ¸Ğ¹ ĞºĞ¾Ğ¼Ğ°Ğ½Ğ´Ğ¾Ğ²Ğ°Ğ½Ğ¸Ğµ ÑÑ‚Ğ°Ğ½Ñ†Ğ¸Ğ¸ ÑĞ²Ğ¾Ğ¸Ğ¼Ğ¸ Ğ¼ĞµÑ‡Ğ¾Ğ¼ Ğ¸ Ğ¼Ğ°Ğ³Ğ¸ĞµĞ¹.
  ğŸ”¥  â‹® Ğ˜Ğ½ĞºĞ²Ğ¸Ğ·Ğ¸Ñ‚Ğ¾Ñ€ - Ğ²Ğ¾Ğ¸Ğ½ Ñ‚ÑŒĞ¼Ñ‹, Ğ¿Ñ€Ğ¸Ğ±Ñ‹Ğ²ÑˆĞ¸Ğ¹ Ğ½Ğ° ÑÑ‚Ğ°Ğ½Ñ†Ğ¸Ñ, Ñ‡Ñ‚Ğ¾Ğ±Ñ‹ ÑƒĞ½Ğ¸Ñ‡Ñ‚Ğ¾Ğ¶Ğ¸Ñ‚ÑŒ Ğ¡Ñ‚Ñ€Ğ°Ğ¶Ğ° ĞšĞ»Ğ¸Ğ½ĞºĞ°.
  ğŸ¦  â‹® S.P.A.F. - ÑĞ»Ğ¸Ğ·ĞµĞ½ÑŒ, Ğ¿Ğ¾Ğ¶Ğ¸Ñ€Ğ°ÑÑ‰Ğ¸Ğ¹ Ñ‡Ğ»ĞµĞ½Ğ¾Ğ² ÑĞºĞ¸Ğ¿Ğ°Ğ¶Ğ° Ñ€Ğ°Ğ´Ğ¸ Ğ¿Ñ€Ğ¾Ğ´Ğ¾Ğ»Ğ¶ĞµĞ½Ğ¸Ñ ÑĞ²Ğ¾ĞµĞ³Ğ¾ Ñ€Ğ¾Ğ´Ğ°.
  ğŸ”Š â‹® TTS - 130 ÑƒĞ½Ğ¸ĞºĞ°Ğ»ÑŒĞ½Ñ‹Ñ… Ğ³Ğ¾Ğ»Ğ¾ÑĞ¾Ğ², Ñ‡Ñ‚Ğ¾Ğ±Ñ‹ Ğ²Ñ‹Ñ€Ğ°Ğ·Ğ¸Ñ‚ÑŒ ÑƒĞ½Ğ¸ĞºĞ°Ğ»ÑŒĞ½Ğ¾ÑÑ‚ÑŒ Ğ²Ğ°ÑˆĞ¸Ñ… Ğ¿ĞµÑ€ÑĞ¾Ğ½Ğ°Ğ¶ĞµĞ¹.
  ğŸŒ â‹® ĞŸĞ¾Ğ»Ğ·Ğ°Ğ½Ğ¸Ğµ - ÑƒĞ½Ğ¸ĞºĞ°Ğ»ÑŒĞ½Ğ°Ñ Ğ¼ĞµÑ…Ğ°Ğ½Ğ¸ĞºĞ°, Ğ¿Ğ¾Ğ·Ğ²Ğ¾Ğ»ÑÑÑ‰Ğ°Ñ Ğ²Ğ°Ğ¼ ÑƒĞ¿Ğ°ÑÑ‚ÑŒ Ğ¸ Ğ¿Ğ¾Ğ»Ğ·Ñ‚Ğ¸.
  ğŸ‘” â‹® ĞÑ‚Ğ·Ñ‹Ğ²Ñ‡Ğ¸Ğ²Ğ°Ñ Ğ°Ğ´Ğ¼Ğ¸Ğ½Ğ¸ÑÑ‚Ñ€Ğ°Ñ†Ğ¸Ñ, ĞºĞ¾Ñ‚Ğ¾Ñ€Ğ°Ñ Ğ¿Ğ¾ĞºĞ°Ğ¶ĞµÑ‚, Ñ€Ğ°ÑÑĞºĞ°Ğ¶ĞµÑ‚ Ğ¸ Ğ¿Ğ¾Ğ¼Ğ¾Ğ¶ĞµÑ‚ Ğ’Ğ°Ğ¼ Ğ¾ÑĞ²Ğ¾Ğ¸Ñ‚ÑÑ.
â€¢â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ âœ§ â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â€¢
                                            ğŸ“š ĞŸÑ€Ğ¸ÑĞ¾ĞµĞ´Ğ¸Ğ½ÑĞ¹Ñ‚ĞµÑÑŒ Ğº Ğ½Ğ°ÑˆĞµĞ¼Ñƒ Ğ´Ñ€ÑƒĞ¶Ğ½Ğ¾Ğ¼Ñƒ ÑĞ¾Ğ¾Ğ±Ñ‰ĞµÑÑ‚Ğ²Ñƒ ğŸ“š"""
map_pool           = "StoriesDefaultMapPool"
lobbyduration      = 210
round_restart_time = 120
contraband_examine = false

[infolinks]
bug_report = "https://github.com/MetalSage/space-stories-14/issues/new/choose"
discord    = "https://discord.gg/space-stories"
forum      = "https://forum.spacestories.club"
github     = "https://github.com/MetalSage/space-stories-14"
patreon    = "https://boosty.to/spacestories14"
wiki       = "https://spacestories.club"
appeal     = "https://discord.gg/space-stories"

[server]
rules_file = "StoriesRuleset"

[shuttle]
auto_call_time             = 0
emergency_dock_time        = 120
emergency_transit_time_min = 30
emergency_transit_time_max = 60

[net]
tickrate        = 30
max_connections = 1024

[vote]
restart_enabled                       = true
preset_enabled                        = false
map_enabled                           = false
restart_not_allowed_when_admin_online = true

[netres]
limit = 10

[admin]
deadmin_on_join             = true
server_ban_hwid_ban_default = false

[ahelp]
admin_prefix = true
admin_prefix_webhook = true

[chat]
rate_limit_period                = 1.5
rate_limit_count                 = 1
rate_limit_announce_admins_delay = 10
max_message_length               = 500

[atmos]
max_explosion_range = 5

[rules]
time = 180.0

[queue]
enabled = true

[biomass]
easy_mode = false

[ic]
flavor_text = true

[procgen]
preload = false

[gateway]
generator_enabled = false

[viewport]
maximum_width = 26
