# UNIVERSE CONFIG

# [config]
# presets = "Stories/universe"

[adminlogs]
server_name = "Space Stories - Universe ğŸ‘©â€ğŸš€"

[game]
hostname         = "ğŸ“š Space Stories - Universe ğŸ‘©â€ğŸš€ [TTS]"
soft_max_players = 130

[hub]
tags = "lang:ru,rp:med,region:eu_e"
